// Copyright MathRunner. All Rights Reserved.

#include "MathRunner.h"
#include "MathRunnerCharacter.h"
#include "MathRunnerPlatform.h"
#include "MathRunnerGameModeBase.h"

#define LOCTEXT_NAMESPACE "FMathRunnerModule"

void FMathRunnerModule::StartupModule()
{
	// Register procedural mesh component module if needed
	FCoreDelegates::OnPostEngineInit.AddLambda([]()
	{
		UE_LOG(LogTemp, Log, TEXT("MathRunner Module Initialized - All assets generated by mathematics!"));
	});
}

void FMathRunnerModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.
}

#undef LOCTEXT_NAMESPACE
	
IMPLEMENT_MODULE(FMathRunnerModule, MathRunner)
